const std::string ShadowLightVertNoNormal=
  "#version 330 core\n"
  "uniform mat4 modelViewMatrix;\n"
  "uniform mat4 modelViewProjectionMatrix;\n"
  "uniform mat4 invModelViewMatrixShadow;\n"
  "layout(location=0) in vec3 Vertex;\n"
  "layout(location=2) in vec2 TexCoord;\n"
  "out vec3 vVert,v0Vert;\n"
  "out vec2 tcVert;\n"
  "void main(void)\n"
  "{\n"
  "  gl_Position=modelViewProjectionMatrix*vec4(Vertex,1);\n"
  "  vec4 vMV=modelViewMatrix*vec4(Vertex,1);\n"
  "  vVert=vec3(vMV);\n"
  "  v0Vert=vec3(invModelViewMatrixShadow*vMV);\n"
  "  tcVert=TexCoord;\n"
  "}\n";
