const std::string MatVecMultVert=
  "#version 330 core\n"
  "uniform int nL;\n"
  "uniform sampler2D DHDL;\n"
  "uniform sampler2D LCoord;\n"
  "layout(location=0) in vec3 Vertex;\n"
  "layout(location=3) in uint id;\n"
  "out vec3 VertexOut;\n"
  "void main(void)\n"
  "{\n"
  "  VertexOut=Vertex;\n"
  "  int offRow=int(id)*3;\n"
  "  for(int i=0; i<nL; i++) {\n"
  "    float LCoordI=texelFetch(LCoord,ivec2(i,0),0).r;\n"
  "    VertexOut+=vec3(texelFetch(DHDL,ivec2(offRow+0,i),0).r,\n"
  "                    texelFetch(DHDL,ivec2(offRow+1,i),0).r,\n"
  "                    texelFetch(DHDL,ivec2(offRow+2,i),0).r)*LCoordI;\n"
  "  }\n"
  "}\n";
