const std::string NormalGeom=
  "#version 330 core\n"
  "layout(triangles) in;\n"
  "layout(triangle_strip,max_vertices=3) out;\n"
  "in vec3 vVert[3],v0Vert[3];\n"
  "in vec2 tcVert[3];\n"
  "out vec3 vN,v,v0;\n"
  "out vec2 tc;\n"
  "void main(void) {\n"
  "  vec3 normal=cross(vVert[1]-vVert[0],vVert[2]-vVert[0]);\n"
  "  normal=normalize(normal);\n"
  "  for(int i=0; i<3; i++) {\n"
  "    gl_Position=gl_in[i].gl_Position;\n"
  "    vN=normal;\n"
  "    v=vVert[i];\n"
  "    v0=v0Vert[i];\n"
  "    tc=tcVert[i];\n"
  "    EmitVertex();\n"
  "  }\n"
  "  EndPrimitive();\n"
  "}\n";
