const std::string ShadowLightVert=
  "#version 330 core\n"
  "uniform mat3 normalMatrix;\n"
  "uniform mat4 modelViewMatrix;\n"
  "uniform mat4 modelViewProjectionMatrix;\n"
  "uniform mat4 invModelViewMatrixShadow;\n"
  "layout(location=0) in vec3 Vertex;\n"
  "layout(location=1) in vec3 Normal;\n"
  "layout(location=2) in vec2 TexCoord;\n"
  "out vec3 vN,v,v0;\n"
  "out vec2 tc;\n"
  "void main(void)\n"
  "{\n"
  "  gl_Position=modelViewProjectionMatrix*vec4(Vertex,1);\n"
  "  vN=normalize(normalMatrix*Normal);\n"
  "  vec4 vMV=modelViewMatrix*vec4(Vertex,1);\n"
  "  v=vec3(vMV);\n"
  "  v0=vec3(invModelViewMatrixShadow*vMV);\n"
  "  tc=TexCoord;\n"
  "}\n";
