const std::string ShadowVert=
  "#version 330 core\n"
  "uniform mat4 modelViewMatrix;\n"
  "uniform mat4 modelViewProjectionMatrix;\n"
  "uniform mat4 invModelViewMatrixShadow;\n"
  "layout(location=0) in vec3 Vertex;\n"
  "layout(location=1) in vec3 Normal;\n"
  "layout(location=2) in vec2 TexCoord;\n"
  "out vec3 FragPos;\n"
  "void main(void)\n"
  "{\n"
  "  vec4 vMV=modelViewMatrix*vec4(Vertex,1);\n"
  "  FragPos=vec3(invModelViewMatrixShadow*vMV);\n"
  "  gl_Position=modelViewProjectionMatrix*vec4(Vertex,1);\n"
  "}\n";
