std::string ThickLineFrag=
  "#version 330 core\n"
  "uniform vec4 color0,color1;\n"
  "flat in vec2 v0,v1;\n"
  "uniform float sz;\n"
  "in vec2 v;\n"
  "out vec4 FragColor;\n"
  "void main (void) {\n"
  "  vec2 v01=v1-v0;\n"
  "  vec2 dir=v-v0;\n"
  "  float len=length(v01),dist=0;\n"
  "  if(len<1e-6) {\n"
  "    dist=length(dir);\n"
  "  } else {\n"
  "    v01/=len;\n"
  "    float vd=dot(v01,dir);\n"
  "    dist=length(dir-vd*v01);\n"
  "  }\n"
  "  if(dist>sz)\n"
  "    discard;\n"
  "  dist/=sz;\n"
  "  FragColor=color0*(1-dist)+color1*dist;\n"
  "}\n";
