std::string ThickLineGeom=
  "#version 330 core\n"
  "uniform float sz;\n"
  "layout(lines) in;\n"
  "layout(triangle_strip,max_vertices=18) out;\n"
  "flat out vec2 v0,v1;\n"
  "out vec2 v;\n"
  "void emit_quad(vec4 vv0,vec4 vv1,vec4 a,vec4 b,vec4 c,vec4 d) {\n"
  "  gl_Position=a;\n"
  "  v=a.xy;\n"
  "  v0=vv0.xy;\n"
  "  v1=vv1.xy;\n"
  "  EmitVertex();\n"
  "  gl_Position=b;\n"
  "  v=b.xy;\n"
  "  v0=vv0.xy;\n"
  "  v1=vv1.xy;\n"
  "  EmitVertex();\n"
  "  gl_Position=c;\n"
  "  v=c.xy;\n"
  "  v0=vv0.xy;\n"
  "  v1=vv1.xy;\n"
  "  EmitVertex();\n"
  "  EndPrimitive();\n"
  "  \n"
  "  gl_Position=a;\n"
  "  v=a.xy;\n"
  "  v0=vv0.xy;\n"
  "  v1=vv1.xy;\n"
  "  EmitVertex();\n"
  "  gl_Position=c;\n"
  "  v=c.xy;\n"
  "  v0=vv0.xy;\n"
  "  v1=vv1.xy;\n"
  "  EmitVertex();\n"
  "  gl_Position=d;\n"
  "  v=d.xy;\n"
  "  v0=vv0.xy;\n"
  "  v1=vv1.xy;\n"
  "  EmitVertex();\n"
  "  EndPrimitive();\n"
  "}\n"
  "void main(void) {\n"
  "  vec4 a=gl_in[0].gl_Position;\n"
  "  vec4 b=gl_in[1].gl_Position;\n"
  "  a=vec4(a.xyz/a.w,1);\n"
  "  b=vec4(b.xyz/b.w,1);\n"
  "  if(a.x<-1 || a.x>1 || a.y<-1 || a.y>1 || a.z<-1 || a.z>1)\n"
  "    return;\n"
  "  if(b.x<-1 || b.x>1 || b.y<-1 || b.y>1 || b.z<-1 || b.z>1)\n"
  "    return;\n"
  "  if(a.x>b.x) {\n"
  "    vec4 tmp=a;\n"
  "    a=b;\n"
  "    b=tmp;\n"
  "  }\n"
  "  emit_quad(a,a,a+vec4(-sz,-sz,0,0),a+vec4( sz,-sz,0,0),a+vec4( sz, sz,0,0),a+vec4(-sz, sz,0,0));\n"
  "  emit_quad(b,b,b+vec4(-sz,-sz,0,0),b+vec4( sz,-sz,0,0),b+vec4( sz, sz,0,0),b+vec4(-sz, sz,0,0));\n"
  "  \n"
  "  vec4 ab=b-a;\n"
  "  if(length(ab)<sz)\n"
  "    return;\n"
  "  vec2 perp=normalize(vec2(-ab.y,ab.x))*sz;\n"
  "  emit_quad(a,b,a-vec4(perp.xy,0,0),b-vec4(perp.xy,0,0),b+vec4(perp.xy,0,0),a+vec4(perp.xy,0,0));\n"
  "}\n";
