IF(NOT Drawer_FOUND)

FIND_PATH(Drawer_INCLUDE_DIR Drawer/Drawer.h
  ${PROJECT_SOURCE_DIR}/include
  ${PROJECT_SOURCE_DIR}
  $ENV{DRAWER_ROOT}/include
  $ENV{DRAWER_ROOT}
  /usr/include
  /usr/local/include)

FIND_LIBRARY(Drawer_LIBRARY NAMES Drawer PATHS 
  ${PROJECT_SOURCE_DIR}/lib
  ${PROJECT_SOURCE_DIR}
  $ENV{DRAWER_ROOT}/lib
  $ENV{DRAWER_ROOT}
  /usr/lib
  /usr/local/lib)

#GLUT/GLFW
FIND_PACKAGE(OpenGL QUIET)
FIND_PACKAGE(GLFW QUIET)
FIND_PACKAGE(GLEW QUIET)
FIND_PACKAGE(PNG QUIET)

IF(Drawer_INCLUDE_DIR AND Drawer_LIBRARY AND OPENGL_FOUND AND GLFW_FOUND AND GLEW_FOUND AND PNG_FOUND)
  set(Drawer_FOUND TRUE)
  set(Drawer_INCLUDE_DIRS ${Drawer_INCLUDE_DIR})
  set(Drawer_LIBRARIES ${Drawer_LIBRARY} ${OPENGL_LIBRARIES} ${GLFW_LIBRARIES} ${GLEW_LIBRARIES} ${PNG_LIBRARIES})
ENDIF(Drawer_INCLUDE_DIR AND Drawer_LIBRARY AND OPENGL_FOUND AND GLFW_FOUND AND GLEW_FOUND AND PNG_FOUND)

MARK_AS_ADVANCED(Drawer_INCLUDE_DIR Drawer_INCLUDE_DIRS Drawer_LIBRARY Drawer_LIBRARIES)

ENDIF(NOT Drawer_FOUND)
